version: '1'
services:
  postgres:
    image: postgres:14
    container_name: task_management_postgres
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: habit_app
      POSTGRES_PASSWORD: 1234
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
