spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/task_management_db
    username: habit_app
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    jwt:
      secret: "MySuperSecretKeyThatIsAtLeast32Characters!"
      expirationTimeInMilliseconds: 600000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: info
    org.flywaydb: debug
